### ISSUE TITLE
lançamento v1.0.0

### ISSUE THREAD

**Issue by thgfrzm** [thgfrzm/ideiaclara#6]
- [x] apresentar marca #1
- [ ] apresentar lista de serviços #2
- [ ] meio de contato #3
- [ ] apresentar redes sociais #4
- [ ] ...?
- [ ] publicar!
